config/routes.rb
Rails.application.routes.draw do
  resources :stress_records do
    get 'search', on: :collection
    post 'set_session', on: :member
  end
  resources :stress_reliefs do
    get 'search', on: :collection
    resources :likes, only: %i[create destroy]
  end
  devise_for :users
  get 'home/index'
  get 'terms_of_service', to: 'home#terms_of_service', as: 'terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  root 'home#index'
end

app/models/stress_record.rb
class StressRecord < ApplicationRecord
  # ストレスレベルの最小値
  STRESS_LEVEL_MIN = 0
  # ストレスレベルの最大値
  STRESS_LEVEL_MAX = 10
  # ストレスレベルのステップ
  STRESS_LEVEL_STEP = 1

  # 選択可能な最小の年
  START_YEAR = 2020
  # 月の範囲
  MONTH_RANGE = 1..12
  # 最初の週
  FIRST_WEEK_NUMBER = 1

  belongs_to :user

  validates :performed, inclusion: { in: [true, false] }
  validates :stress_relief_date, :before_stress_level, :after_stress_level, presence: true
  validates :before_stress_level, inclusion: { in: STRESS_LEVEL_MIN..STRESS_LEVEL_MAX }
  validates :after_stress_level, inclusion: { in: STRESS_LEVEL_MIN..STRESS_LEVEL_MAX }
  validates :title, length: { maximum: 50 }

  scope :for_date_range, ->(start_date, end_date) { where(stress_relief_date: start_date..end_date) }

  # 指定の日付範囲のストレスレベルのデータを取得
  def self.get_data_for_range(records, range, start_date)
    # 最新のストレス解消日を取得するか、存在しない場合は指定の開始日を使用
    latest_date = records.maximum(:stress_relief_date) || start_date

    # 表示範囲が週か月によって開始日を計算
    range_start_date = if range == 'week'
                         start_date
                       else
                         start_date.beginning_of_month
                       end

    # 指定の範囲内で、日ごとのストレスレベルの変動を計算
    records.where(stress_relief_date: range_start_date..latest_date)
           .group_by_day(:stress_relief_date, series: false)
           .average('after_stress_level - before_stress_level')
  end

  # 指定の年月の各週の開始日と終了日を計算
  def self.calculate_weeks_for_month(year, month)
    first_day_of_month = Date.new(year, month, 1)
    last_day_of_month = first_day_of_month.end_of_month

    weeks = []
    start_day = first_day_of_month
    # 指定の月内で各週の開始日と終了日をリストアップ
    while start_day <= last_day_of_month
      end_day = [start_day.end_of_week(:sunday), last_day_of_month].min
      weeks << { start: start_day, end: end_day }
      start_day = end_day + 1.day
    end
    weeks
  end

  # 現在の日付がどの週に該当するかを特定
  def self.find_current_week_number(weeks, today)
    index = weeks.find_index { |week| week[:start] <= today && week[:end] >= today }
    index ? index + 1 : 1
  end

  # ユーザーと表示範囲、日付に基づいてデータを取得
  def self.get_stress_data_for_user(user, range, start_date, end_date)
    records = records_for_user_and_date_range(user, start_date, end_date).where(performed: true)
    get_data_for_range(records, range, start_date)
  end

  # ユーザーと日付範囲に基づいてストレスレコードを取得
  def self.records_for_user_and_date_range(user, start_date, end_date)
    where(user:, stress_relief_date: start_date..end_date)
  end

  # 月または週の範囲を計算
  def self.calculate_date_range(selected_year, selected_month, range, week_number, weeks)
    if range == 'week' && week_number.present?
      week_number = week_number.to_i
      start_day = weeks[week_number - 1][:start].beginning_of_day
      end_day = weeks[week_number - 1][:end].end_of_day
    else
      start_day = Date.new(selected_year, selected_month, 1).beginning_of_day
      end_day = start_day.end_of_month.end_of_day
    end
    [start_day, end_day]
  end
end

app/controllers/stress_records_controller.rb
class StressRecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stress_record, only: %i[show edit update destroy set_session]
  before_action :set_date_params, only: [:index]
  before_action :set_range, only: [:index]
  before_action :set_stress_reliefs, only: %i[new edit]

  def index
    calculate_weeks_and_dates
    fetch_stress_records
  end

  def show; end

  def new
    @stress_record = StressRecord.new
    @stress_record.stress_relief_date = Time.zone.today

    return unless permitted_params[:stress_relief_id]

    stress_relief = StressRelief.find(permitted_params[:stress_relief_id])
    @stress_record.title = stress_relief.title
    @stress_record.detail = stress_relief.detail
  end

  def edit; end

  def create
    @stress_record = current_user.stress_records.new(stress_record_params)

    if @stress_record.save
      redirect_to stress_record_path(@stress_record), notice: t('.success')
    else
      set_stress_reliefs
      flash.now[:alert] = t('.error')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @stress_record.update(stress_record_params)
      redirect_to stress_record_path(@stress_record), notice: t('.success')
    else
      flash.now[:alert] = t('.error')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @stress_record.destroy
    redirect_to stress_records_url, notice: t('.success')
  end

  def search
    @search_results = StressRelief.where('title LIKE ?', "%#{params[:query]}%").limit(5)
  end

  def set_session
    session[:shared_title] = @stress_record.title
    session[:shared_detail] = @stress_record.detail
    redirect_to new_stress_relief_path
  end

  private

  def set_date_params
    # 現在の日付を取得
    today = Time.zone.today
    # ユーザーが選択した年と月を取得、または現在の年と月をデフォルトとして使用
    @selected_year = (params[:year] || today.year).to_i
    @selected_month = (params[:month] || today.month).to_i
  end

  def set_range
    # 表示範囲（週または月）を取得し、セッションに保存
    @range = if %w[week month].include?(params[:range])
               params[:range]
             else
               session[:range] || 'week'
             end
    session[:range] = @range
  end

  # 週と日付の範囲を計算
  def calculate_weeks_and_dates
    @weeks = StressRecord.calculate_weeks_for_month(@selected_year, @selected_month)
    @week_number = determine_week_number
    @start_date, @end_date = StressRecord.calculate_date_range(@selected_year,
                                                               @selected_month, @range, @week_number, @weeks)
  end

  # 週番号の決定
  def determine_week_number
    if params[:week_number].present?
      week_number = params[:week_number].to_i
      # 週番号がその月の週の数を超えている場合、最初の週をリセット
      week_number <= @weeks.length ? week_number : StressRecord::FIRST_WEEK_NUMBER
    else
      StressRecord.find_current_week_number(@weeks, Time.zone.today)
    end
  end

  # ストレスレコードの取得
  def fetch_stress_records
    # テーブル表示用のデータ取得
    @stress_records = StressRecord.records_for_user_and_date_range(current_user, @start_date, @end_date)
                                  .order(stress_relief_date: :asc)
    # グラフ表示用のデータ取得
    @data = StressRecord.get_stress_data_for_user(current_user, @range, @start_date, @end_date)
  end

  def set_stress_reliefs
    @stress_reliefs = if params[:query].present?
                        StressRelief.preload(:user, :tags).order(created_at: :desc).page(params[:page])
                                    .where('title LIKE ?', "%#{params[:query]}%")
                      else
                        StressRelief.preload(:user, :tags).order(created_at: :desc).page(params[:page])
                      end
  end

  def permitted_params
    params.permit(:stress_relief_id)
  end

  def set_stress_record
    @stress_record = current_user.stress_records.find(params[:id])
  end

  def stress_record_params
    params.require(:stress_record).permit(
      :stress_relief_date,
      :title,
      :detail,
      :before_stress_level,
      :after_stress_level,
      :impression,
      :performed
    )
  end
end

app/helpers/stress_records_helper.rb
module StressRecordsHelper
end

app/views/stress_records/_form.html.erb
<%= form_with(model: stress_record, class: "contents") do |form| %>
  <% if stress_record.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= t('stress_records.form.errors', count: stress_record.errors.count) %></h2>

      <ul>
        <% stress_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :stress_relief_date, class: "inline-block" %>
    <span class="text-red-500">*</span>
    <%= form.date_field :stress_relief_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-2/5" %>
  </div>

  <div class="my-5 text-center">
    <button type="button" data-action="open-modal" class="bg-blue-800 hover:bg-blue-700 text-white rounded-md px-4 py-2"><%= t('stress_records.form.select_from_recommendations') %></button>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: t('stress_records.form.title_max_length'), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :detail %>
    <%= form.text_area :detail, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full mb-10" %>
  </div>

  <div class="my-5 text-center font-bold mb-10">
    <%= t('stress_records.form.perform_stress_relief') %>
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-circle btn-ghost btn-xs text-info">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
      </label>
      <div tabindex="0" class="card compact dropdown-content z-[1] shadow bg-base-100 rounded-box w-64">
        <div class="card-body">
          <h2 class="card-title"><%= t('stress_records.instructions.card_title') %></h2>
          <p class="text-left"><%= t('stress_records.instructions.step1') %></p>
          <p class="text-left"><%= t('stress_records.instructions.step2') %></p>
          <p class="text-left"><%= t('stress_records.instructions.step3') %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="my-5 flex flex-col md:flex-row items-center justify-between mb-8">
    <%= render 'stress_slider', form: form, label_symbol: :before_stress_level, label_text: t('stress_records.stress_slider.before_stress_level'), stress_value: stress_record.before_stress_level || StressRecord::STRESS_LEVEL_MIN, margin_class: "mb-4 md:mb-0 md:mr-4 text-red-500" %>

    <div class="hidden md:block mx-2 text-6xl">➡</div>
    <div class="md:hidden my-2 text-6xl">⬇︎</div>

    <%= render 'stress_slider', form: form, label_symbol: :after_stress_level, label_text: t('stress_records.stress_slider.after_stress_level'), stress_value: stress_record.after_stress_level || StressRecord::STRESS_LEVEL_MIN, margin_class: "mt-4 md:mt-0 md:ml-4 text-blue-500" %>
  </div>

  <div class="my-5">
    <%= form.label :impression %>
    <%= form.text_area :impression, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-12 flex items-center justify-center">
    <%= form.check_box :performed, class: "checkbox mr-2" %>
    <%= form.label :performed, class: "font-medium" %>
  </div>

  <div class="inline">
    <%= form.submit stress_record.new_record? ? t('defaults.create') : t('defaults.update'), class: "rounded-lg py-3 px-5 bg-blue-800 hover:bg-blue-700 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

<div data-modal-target="modal" class="fixed top-0 left-0 w-full h-full flex justify-center items-center bg-black bg-opacity-50 hidden">
  <div class="bg-gray-100 rounded-lg p-5 w-4/5 h-5/6 overflow-y-auto">
    <h2 class="text-2xl font-bold text-center mb-4"><%= t('modal.select_stress_relief') %></h2>
    <div class="text-center mb-6">
      <% form_action = @stress_record.new_record? ? new_stress_record_path : edit_stress_record_path(@stress_record) %>
      <form action="<%= form_action %>" method="get" data-turbo-action="replace" data-turbo-frame="modal_content">
        <div class="relative w-4/5 inline-block">
          <input type="text" name="query" value="<%= params[:query] %>" data-autocomplete-input="stress_record" placeholder="<%= t('search.input_placeholder') %>" class="border border-gray-300 p-2 rounded-md w-full shadow-sm focus:ring-indigo-700 focus:border-indigo-700 box-sizing:border-box">
          <div id="autocomplete-results" class="overflow-wrap break-word absolute top-full left-0 mt-2 w-full bg-white border border-gray-300 p-2 rounded-md shadow-sm divide-y divide-gray-300 hidden z-50 box-sizing:border-box overflow-y-auto"></div>
        </div>
        <button type="submit" class="inline-block ml-2 bg-indigo-700 text-white p-2 rounded-md hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-700 focus:ring-opacity-50 box-sizing:border-box">
          <%= t('defaults.search_button') %>
        </button>
      </form>
    </div>
    <%= render 'stress_reliefs/modal_stress_reliefs' %>
    <button data-action="close-modal" class="mt-4 bg-red-500 hover:bg-red-400 text-white rounded-md px-4 py-2"><%= t('modal.cancel') %></button>
  </div>
</div>

app/views/stress_records/_search_results.html.erb
<ul>
<% results.each do |result| %>
  <li class="w-full hover:bg-gray-300 truncate" data-result-title="<%= result.title %>"style="white-space: nowrap; overflow-x: hidden; text-overflow: ellipsis;">
    <%= result.title %>
  </li>
<% end %>
</ul>

app/views/stress_records/_stress_record.html.erb
<div id="<%= dom_id stress_record %>" class="max-w-3xl mx-auto">
  <div class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.stress_record.stress_relief_date') %></strong>
    <p class="border border-gray-400 bg-gray-200 rounded-md p-2 w-40"><%= stress_record.stress_relief_date.to_date %></p>
  </div>

  <div class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.stress_record.title') %></strong>
    <div class="border border-gray-400 bg-gray-200 rounded-md p-2 max-w-full break-words mb-10 min-h-[40px] overflow-y-auto">
      <%= simple_format stress_record.title %>
    </div>
  </div>

  <div class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.stress_record.detail') %></strong>
    <div class="border border-gray-400 bg-gray-200 rounded-md p-2 max-w-full break-words mb-10 min-h-[100px] overflow-y-auto">
      <%= simple_format stress_record.detail %>
    </div>
  </div>

  <div class="my-5 text-center font-bold mb-10">
    <%= t('stress_records.form.perform_stress_relief') %>
  </div>

  <div class="my-5 flex flex-col md:flex-row justify-between mb-8">
    <div class="relative w-full md:w-1/3 mb-4 md:mb-0 md:mr-4 md:ml-14 text-red-500">
      <label class="block text-center mb-10 text-lg"><%= t('stress_records.stress_slider.before_stress_level') %></label>
      <div class="text-center mb-4 border border-gray-400 bg-gray-200 rounded-md h-10 flex items-center justify-center">
        <span class="text-red-500"><%= stress_record.before_stress_level %></span>
      </div>
      <input type="range" min="<%= StressRecord::STRESS_LEVEL_MIN %>" max="<%= StressRecord::STRESS_LEVEL_MAX %>" value="<%= stress_record.before_stress_level %>" class="range range-error w-full mb-4" step="<%= StressRecord::STRESS_LEVEL_STEP %>" disabled>
      <div class="w-full flex justify-between px-2 items-center">
        <span class="flex-shrink-0 text-xs" style="flex-basis: 35%; text-align: left;"><%= t('stress_records.stress_slider.no_stress') %></span>
        <span class="flex-shrink-0 text-xs" style="flex-basis: 35%; text-align: right;"><%= t('stress_records.stress_slider.extreme_stress') %></span>
      </div>
    </div>

    <div class="hidden md:flex flex-col justify-center items-center mx-2 my-4">
      <div class="text-6xl">➡︎</div>
    </div>
    <div class="md:hidden flex flex-col justify-center items-center mx-2 my-4">
      <div class="text-6xl">⬇︎</div>
    </div>

    <div class="relative w-full md:w-1/3 mt-4 md:mt-0 md:ml-4 md:mr-14 text-blue-500">
      <label class="block text-center mb-10 text-lg"><%= t('stress_records.stress_slider.after_stress_level') %></label>
      <div class="text-center mb-4 border border-gray-400 bg-gray-200 rounded-md h-10 flex items-center justify-center">
        <span class="text-blue-500"><%= stress_record.after_stress_level %></span>
      </div>
      <input type="range" min="<%= StressRecord::STRESS_LEVEL_MIN %>" max="<%= StressRecord::STRESS_LEVEL_MAX %>" value="<%= stress_record.after_stress_level %>" class="range range-info w-full mb-4" step="<%= StressRecord::STRESS_LEVEL_STEP %>" disabled>
      <div class="w-full flex justify-between px-2 items-center">
        <span class="flex-shrink-0 text-xs" style="flex-basis: 35%; text-align: left;"><%= t('stress_records.stress_slider.no_stress') %></span>
        <span class="flex-shrink-0 text-xs" style="flex-basis: 35%; text-align: right;"><%= t('stress_records.stress_slider.extreme_stress') %></span>
      </div>
    </div>
  </div>

  <div class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.stress_record.impression') %></strong>
    <div class="border border-gray-400 bg-gray-200 rounded-md p-2 max-w-full break-words min-h-[100px] overflow-y-auto">
      <%= simple_format stress_record.impression %>
    </div>
  </div>

  <div class="my-12 flex items-center justify-center">
    <input type="checkbox" <%= 'checked' if stress_record.performed %> disabled class="checkbox mr-2" />
    <strong class="font-medium"><%= t('activerecord.attributes.stress_record.performed') %></strong>
  </div>
</div>

app/views/stress_records/_stress_records_table.html.erb
<div class="my-5 max-w-5xl mx-auto overflow-x-auto">
  <table class="w-full bg-white rounded-lg">
    <thead class="bg-gray-200">
      <tr>
        <th class="py-2 px-4 text-center w-20"><%= t('stress_records.index.stress_relief_date') %></th>
        <th class="py-2 px-4 text-center w-32">
          <div><%= t('stress_records.index.performed') %></div>
          <div>✔️/-</div>
        </th>
        <th class="py-2 px-4 text-center w-3/6 hidden md:table-cell"><%= t('stress_records.index.title_stress_relief') %></th>
        <th colspan="2" class="text-center">
          <div class="text-center"><%= t('stress_records.index.stress_level') %></div>
          <div class="grid grid-cols-2">
            <div class="py-2 px-4 text-center w-30"><%= t('stress_records.index.before') %></div>
            <div class="py-2 px-4 text-center w-30"><%= t('stress_records.index.after') %></div>
          </div>
        </th>
        <th class="py-2 px-4 text-right" style="min-width: 50px;"></th>
      </tr>
    </thead>
    <tbody>
      <% stress_records.each do |stress_record| %>
        <tr id="stress_record_<%= stress_record.id %>" class="hover:bg-gray-50 transition-colors duration-200 border">
          <td class="py-2 px-4 w-20 cursor-pointer" onclick="location.href='<%= stress_record_path(stress_record) %>'"><%= stress_record.stress_relief_date.strftime('%m/%d') %></td>
          <td class="py-2 px-4 w-32 text-center cursor-pointer" onclick="location.href='<%= stress_record_path(stress_record) %>'"><%= stress_record.performed ? '✔️' : '-' %></td>
          <td class="py-2 px-4 w-3/6 break-all cursor-pointer hidden md:table-cell" onclick="location.href='<%= stress_record_path(stress_record) %>'"><%= stress_record.title %></td>
          <td class="py-2 px-4 text-center cursor-pointer" onclick="location.href='<%= stress_record_path(stress_record) %>'"><%= stress_record.before_stress_level %></td>
          <td class="py-2 px-4 w-30 text-center cursor-pointer" onclick="location.href='<%= stress_record_path(stress_record) %>'">
            <%= stress_record.performed ? stress_record.after_stress_level : '-' %>
          </td>
          <td class="py-2 px-4 text-right" style="vertical-align: middle;">
            <%= link_to stress_record_path(stress_record), method: :delete, data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_message') }, class: "p-1 bg-transparent hover:bg-red-100 rounded transition-colors duration-200 flex items-center justify-center" do %>
              <%= image_tag 'rubbish.png', alt: 'Delete', class: 'w-5 h-5' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/stress_records/edit.html.erb
<div class="mx-auto md:w-2/3 w-full px-4">
  <h1 class="font-bold text-4xl mt-4"><%= t('stress_records.edit.editing_stress_record') %></h1>

  <%= render "form", stress_record: @stress_record %>

  <%= link_to t('stress_records.edit.show_stress_record'), @stress_record, class: "ml-2 rounded-lg py-3 px-5 mb-4 bg-gray-300 hover:bg-gray-200 inline-block font-medium" %>
</div>

app/views/stress_records/index.html.erb
<div class="w-full px-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-12 max-w-5xl mx-auto">
    <div class="flex justify-between items-center mb-5">
      <h1 class="font-bold text-4xl mt-4"><%= t('stress_records.index.title') %></h1>
      <%= link_to t('stress_records.index.new_stress_record'), new_stress_record_path, class: "rounded-lg py-3 px-5 mt-4 bg-blue-800 hover:bg-blue-700 text-white font-medium" %>
    </div>

    <%= form_with url: stress_records_path, method: :get do |f| %>
      <div class="flex items-center space-x-2 mb-5">
        <%= f.select :year, options_for_select((StressRecord::START_YEAR..Time.zone.now.year).to_a.reverse, selected: params[:year] || Time.zone.now.year), {}, class: "form-select" %>
        <%= f.select :month, options_for_select((StressRecord::MONTH_RANGE).to_a, selected: params[:month] || Time.zone.now.month), {}, class: "form-select" %>
      
        <% if @range == "week" %>
          <%= f.select :week_number, options_for_select((StressRecord::FIRST_WEEK_NUMBER..@weeks.length).map { |i| [t('stress_records.index.nth_week', week_number: i), i] }, selected: params[:week_number] || @week_number), {}, class: "form-select" %>
        <% end %>
        
        <%= f.submit t('defaults.search_button'), class: "rounded-lg py-3 px-5 bg-indigo-700 hover:bg-indigo-600 text-white font-medium" %>
      </div>
    <% end %>
  </div>

  <div class="my-5 max-w-5xl mx-auto bg-white p-4 rounded-lg relative">
    <select class="select select-bordered bg-white w-auto max-w-sm absolute top-4 left-4 z-10" data-controller="records-chart" data-action="change->records-chart#changeRange">
      <option value="week" <%= @range == "week" ? 'selected' : '' %>><%= t('stress_records.index.weekly') %></option>
      <option value="month" <%= @range == "month" ? 'selected' : '' %>><%= t('stress_records.index.monthly') %></option>
    </select>
    <div class="flex flex-col justify-between items-center pt-16 pb-4">
      <div class="flex items-center mb-4">
        <h2 class="font-bold text-2xl mr-2"><%= t('stress_records.index.stress_level_fluctuation') %></h2>
        
        <div class="dropdown dropdown-left">
          <label tabindex="0" class="btn btn-circle btn-ghost btn-xs text-blue-500">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          </label>
          <div tabindex="0" class="dropdown-content card compact z-[1] shadow bg-base-100 rounded-box w-64">
            <div class="card-body">
              <h2 class="card-title"><%= t('stress_records.index.graph_description') %></h2>
              <p class="text-left"><%= t('stress_records.index.graph_detail') %></p>
            </div>
          </div>
        </div>
      </div>
      <% if @range == "week" && @week_number.present? %>
        <p class="text-center"><%= t('stress_records.index.nth_week', week_number: @week_number) %>: <%= @weeks[@week_number - 1][:start].strftime('%Y-%m-%d') %> 〜 <%= @weeks[@week_number - 1][:end].strftime('%Y-%m-%d') %></p>
      <% end %>
    </div>
    <%= line_chart @data, height: "400px" %>
  </div>

  <div id="stress-records-table" class="max-w-5xl mx-auto">
    <%= render 'stress_records/stress_records_table', stress_records: @stress_records %>
  </div>
</div>

app/views/stress_records/new.html.erb
<div class="mx-auto md:w-2/3 w-full px-4">
  <h1 class="font-bold text-4xl mt-4"><%= t('stress_records.new.title') %></h1>

  <%= render "form", stress_record: @stress_record %>

  <%= link_to t('stress_records.new.back_to_stress_records'), stress_records_path, class: "ml-2 rounded-lg py-3 px-5 mb-4 bg-gray-300 hover:bg-gray-200 inline-block font-medium" %>
</div>

app/views/stress_records/search.turbo_stream.erb
<%= turbo_stream.update "autocomplete-results", partial: "stress_records/search_results", locals: { results: @search_results } %>

app/views/stress_records/show.html.erb
<div class="mx-auto md:w-2/3 w-full px-4">
  <div class="mx-auto">
    <div class="flex justify-between items-center mt-4">
      <h1 class="font-bold text-4xl"><%= t('stress_records.show.title') %></h1>
      <div class="flex items-center">
        <%= link_to t('defaults.edit'), edit_stress_record_path(@stress_record), class: "rounded-lg py-3 px-5 bg-emerald-600 hover:bg-emerald-500 inline-block text-white font-medium mr-2" %>
        <%= link_to t('defaults.destroy'), stress_record_path(@stress_record), data: { turbo_method: 'delete', turbo_confirm: t('defaults.delete_message') }, class: "rounded-lg py-3 px-5 bg-red-500 hover:bg-red-400 text-white font-medium" %>
      </div>
    </div>
    
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="text-center mt-4">
      <%= button_to t('stress_records.show.share_as_recommendation'), set_session_stress_record_path(@stress_record), method: :post, class: "bg-blue-800 hover:bg-blue-700 text-white py-2 px-5 rounded-lg transition duration-300" %>
    </div>

    <%= render @stress_record %>
  </div>
</div>