config/routes.rb
Rails.application.routes.draw do
  resources :stress_records do
    get 'search', on: :collection
    post 'set_session', on: :member
  end
  resources :stress_reliefs do
    get 'search', on: :collection
    resources :likes, only: %i[create destroy]
  end
  devise_for :users
  get 'home/index'
  get 'terms_of_service', to: 'home#terms_of_service', as: 'terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  root 'home#index'
end

app/models/stress_relief.rb
class StressRelief < ApplicationRecord
  # 難易度の初期値
  DEFAULT_DIFFICULTY = 1
  # 難易度の最小値
  MIN_DIFFICULTY = 1
  # 難易度の最大値
  MAX_DIFFICULTY = 3

  # 画像設定する際の各難易度別の画像の枚数
  NUMBER_OF_IMAGES = 4

  # あなたへおすすめのストレス解消法の表示件数
  MAX_RECOMMENDED_COUNT = 3
  # いいねが多いストレス解消法を取得する上限の件数
  TOP_STRESS_RELIEFS_LIMIT = 5

  belongs_to :user
  has_many :stress_relief_tags, dependent: :destroy
  has_many :tags, through: :stress_relief_tags
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :detail, presence: true
  validates :difficulty, presence: true, inclusion: { in: MIN_DIFFICULTY..MAX_DIFFICULTY }
  validate :check_for_invalid_tags

  # タグ名を配列で取得
  def tag_names
    # 一時保存されたタグ名があればそれを使用し、なければタグ名を取得する。
    @raw_tag_names.present? ? @raw_tag_names.split(',').map(&:strip) : tags.map(&:name)
  end

  # タグ名を設定する。既存のタグは再利用し、存在しないタグは新規作成する。
  def tag_names=(names)
    # 受け取ったタグ名を一時保存
    @raw_tag_names = names.strip
    tag_objects = []
    @invalid_tag_detected = false

    process_tags(names.split(',').compact_blank.uniq, tag_objects)

    # 無効なタグがない場合、タグを設定
    self.tags = tag_objects unless @invalid_tag_detected
  end

  # タグ名の配列を受け取り、それに対応するタグオブジェクトを取得または新規作成する。
  def process_tags(names_array, tag_objects)
    names_array.each do |name|
      tag = Tag.find_or_initialize_by(name: name) # rubocop:disable Style/HashSyntax
      if tag.new_record? && !tag.valid?
        errors.add(:tag_names, tag.errors.full_messages.join(', '))
        @invalid_tag_detected = true
      else
        tag.save
        tag_objects << tag
      end
    end
  end

  # 無効なタグがある場合、エラーを追加
  def check_for_invalid_tags
    return unless @invalid_tag_detected

    errors.add(:base, :invalid_tags)
  end

  # いいねをしているかどうかを確認する。
  def liked_by?(like, user)
    like.pluck(:user_id).include?(user)
  end

  # いいねのレコードを返す。
  def user_like(user)
    likes.find_by(user_id: user.id)
  end

  # おすすめのストレス解消法を取得する。
  def self.recommended_stress_reliefs(user)
    # ユーザーがいいねした投稿のユーザーIDを取得し、重複を排除する。
    users_who_liked_my_posts = user.stress_reliefs.joins(:likes).pluck('likes.user_id').uniq

    # おすすめのストレス解消法を取得
    stress_reliefs_from_liked_users = if users_who_liked_my_posts.present?
                                        eager_load(:user, :tags, :likes)
                                          .where(user_id: users_who_liked_my_posts)
                                          .where.not(user_id: user.id)
                                          .to_a.sample(MAX_RECOMMENDED_COUNT)
                                      else
                                        []
                                      end

    fill_top_stress_reliefs(stress_reliefs_from_liked_users, user)
  end

  # おすすめのリストが足りない場合、いいねが多い投稿を追加
  def self.fill_top_stress_reliefs(stress_reliefs, user)
    if stress_reliefs.size < MAX_RECOMMENDED_COUNT
      top_stress_reliefs = left_joins(:likes)
                           .group(:id)
                           .order('COUNT(likes.id) DESC')
                           .limit(TOP_STRESS_RELIEFS_LIMIT).where.not(user_id: user.id)
                           .pluck(:id).sample(MAX_RECOMMENDED_COUNT - stress_reliefs.size)
      # 取得した投稿を既存のおすすめリストに追加
      stress_reliefs + where(id: top_stress_reliefs).eager_load(:user, :tags, :likes)
    else
      stress_reliefs
    end
  end
end

app/controllers/stress_reliefs_controller.rb
class StressReliefsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show search]
  before_action :set_stress_relief, only: %i[show edit update destroy]
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def index
    @stress_reliefs = select_stress_reliefs
  end

  def show; end

  def new
    @stress_relief = StressRelief.new
    @stress_relief.difficulty ||= StressRelief::DEFAULT_DIFFICULTY
    @stress_relief.title = session.delete(:shared_title)
    @stress_relief.detail = session.delete(:shared_detail)
  end

  def edit; end

  def create
    @stress_relief = current_user.stress_reliefs.build(stress_relief_params)

    if @stress_relief.save
      redirect_to stress_relief_path(@stress_relief), notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @stress_relief.update(stress_relief_params)
      redirect_to stress_relief_path(@stress_relief), notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @stress_relief.destroy
    redirect_to stress_reliefs_path, notice: t('.success')
  end

  def search
    @search_results = StressRelief.where('title LIKE ?', "%#{params[:query]}%").limit(5)
  end

  private

  def select_stress_reliefs
    if params[:query].present?
      search_stress_reliefs
    elsif user_liked_stress_relief?
      liked_stress_reliefs
    elsif recommend_param?
      recommended_stress_reliefs
    else
      default_stress_reliefs
    end
  end

  def set_stress_relief
    preload_associations = [:tags]
    @stress_relief = if action_name == 'edit'
                       StressRelief.preload(*preload_associations).find(params[:id])
                     elsif user_signed_in?
                       StressRelief.preload(:user, :likes, *preload_associations).find(params[:id])
                     else
                       StressRelief.preload(:user, *preload_associations).find(params[:id])
                     end
  end

  def search_stress_reliefs
    StressRelief.preload(:user, :tags).where('title LIKE ?', "%#{params[:query]}%")
                .order(created_at: :desc).page(params[:page])
  end

  def user_liked_stress_relief?
    params[:liked] == 'true' && user_signed_in?
  end

  def liked_stress_reliefs
    stress_reliefs_with_pagination = StressRelief.joins(:likes).where(likes: { user_id: current_user.id })
                                                 .preload(:tags, :user).page(params[:page])

    # ページが存在しない場合は、最初のページにリダイレクト
    if stress_reliefs_with_pagination.empty? && params[:page].present?
      redirect_to stress_reliefs_path(liked: true) and return
    end

    @stress_reliefs = stress_reliefs_with_pagination
    render 'user_liked'
  end

  def recommend_param?
    params[:recommend] == 'true' && user_signed_in?
  end

  def recommended_stress_reliefs
    @stress_reliefs = StressRelief.recommended_stress_reliefs(current_user)
    render 'recommend' and return
  end

  def default_stress_reliefs
    StressRelief.preload(:user, :tags).order(created_at: :desc).page(params[:page])
  end

  def ensure_correct_user
    is_correct_user = @stress_relief.user_id == current_user.id
    redirect_to stress_reliefs_path, alert: t('stress_reliefs.unauthorized') unless is_correct_user
  end

  def stress_relief_params
    params.require(:stress_relief).permit(:title, :detail, :difficulty, :tag_names, :selected_image)
  end
end

app/helpers/stress_reliefs_helper.rb
module StressReliefsHelper
end

app/views/stress_reliefs/_difficulty_stars.html.erb
<div class="flex">
  <% (StressRelief::MIN_DIFFICULTY..StressRelief::MAX_DIFFICULTY).each do |rating| %>
    <span class="<%= rating <= local_assigns[:difficulty] ? "text-yellow-500" : "text-gray-400" %>">★</span>
  <% end %>
</div>

app/views/stress_reliefs/_form.html.erb
<%= form_with(model: stress_relief, class: "contents") do |form| %>
  <% if stress_relief.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= t('stress_reliefs.form.errors', count: stress_relief.errors.count) %></h2>

      <ul>
        <% stress_relief.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title, class: "inline-block" %>
    <span class="text-red-500">*</span>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: t('stress_reliefs.form.title_max_length') %>
  </div>

  <div class="my-5">
    <%= form.label :detail, class: "inline-block" %>
    <span class="text-red-500">*</span>
    <%= form.text_area :detail, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 flex">
    <div class="mr-5">
      <%= form.label :difficulty, class: "block text-lg font-medium mb-2 inline-block" %>
      <span class="text-red-500">*</span>
      <div class="flex">
        <% (StressRelief::MIN_DIFFICULTY..StressRelief::MAX_DIFFICULTY).each do |rating| %>
          <%= form.radio_button :difficulty, rating, checked: rating == stress_relief.difficulty, class: "hidden star-rating", id: "rating_#{rating}" %>
          <%= label_tag "rating_#{rating}", "★", class: "star-label text-xl cursor-pointer hover:text-yellow-500", data: { default_image_path: asset_path("stress_relief_board#{rating}.webp") } %>
        <% end %>
      </div>
    </div>
    <div class="flex-grow">
      <%= button_tag t('stress_reliefs.form.set_difficulty_and_image'), type: 'button', id: 'openModalButton', class: 'py-2 px-4 bg-blue-800 hover:bg-blue-700 text-white rounded-lg ml-3' %>
    </div>
  </div>

  <%= form.hidden_field :temporary_selected_image, id: 'temporarySelectedImage' %>
  <%= form.hidden_field :difficulty, id: 'selectedDifficulty', value: stress_relief.difficulty %>

  <div class="my-5">
    <% image_file = stress_relief.selected_image.presence || "stress_relief_board#{stress_relief.difficulty}.webp" %>
    <%= image_tag(asset_path(image_file), id: 'previewImage', class: 'w-64 h-auto object-cover mb-4') %>
    <%= form.hidden_field :selected_image, id: 'selectedImage' %>
  </div>

  <div class="my-5">
    <%= form.label :tag_names, StressRelief.human_attribute_name(:tag_names) %>
    <%= form.text_field :tag_names, value: @stress_relief.tag_names.join(', '), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: t('stress_reliefs.form.placeholders.tag_names') %>
  </div>

  <div class="inline">
    <%= form.submit stress_relief.new_record? ? t('stress_reliefs.form.submit') : t('defaults.update'), class: "rounded-lg py-3 px-5 bg-blue-800 hover:bg-blue-700 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

<%= render 'image_modal' %>

app/views/stress_reliefs/_image_modal.html.erb
<div id="imageModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full">
  <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
    <p class="text-sm mb-2 font-bold"><%= t('modal.image_selection.instruction') %></p>
    <select id="difficultySelect" class="select select-bordered w-full">
      <% (StressRelief::MIN_DIFFICULTY..StressRelief::MAX_DIFFICULTY).each do |difficulty| %>
        <option value="<%= difficulty %>"><%= t('activerecord.attributes.stress_relief.difficulty') %> <%= difficulty %></option>
      <% end %>
    </select>

    <div id="imageSelection" class="mt-4 grid grid-cols-2 gap-4"></div>

    <%= button_tag t('modal.ok'), type: 'button', id: 'confirmSelectionButton', class: 'mt-3 bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-2 px-4 rounded' %>
    <button id="closeModal" class="mt-3 bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 rounded"><%= t('modal.cancel') %></button>

    <% (StressRelief::MIN_DIFFICULTY..StressRelief::MAX_DIFFICULTY).each do |difficulty| %>
      <div id="imagePathsForDifficulty<%= difficulty %>" class="hidden">
        <% (1..StressRelief::NUMBER_OF_IMAGES).each do |image_number| %>
          <span data-path="<%= asset_path("stress_relief_board#{difficulty}_#{image_number}.webp") %>"></span>
        <% end %>
        <span id="defaultImagePath<%= difficulty %>" data-path="<%= asset_path("stress_relief_board#{difficulty}.webp") %>"></span>
      </div>
    <% end %>
  </div>
</div>

app/views/stress_reliefs/_like_icon_filled.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7 mr-1" viewBox="0 0 24 24" fill="currentColor">
  <path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
</svg>

app/views/stress_reliefs/_like_icon_outline.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="h-7 w-7 mr-1 stroke-current">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
</svg>

app/views/stress_reliefs/_like_link_index.html.erb
<% if current_user %>
  <% if stress_relief.liked_by?(stress_relief.likes, current_user.id) %>
    <%= link_to stress_relief_like_path(stress_relief, stress_relief.user_like(current_user)), method: :delete, data: { turbo_frame: "like_#{stress_relief.id}" }, class: "text-pink-500 hover:text-pink-300 transition duration-100 cursor-pointer mr-2 flex items-center", data: { turbo_method: "delete" } do %>
      <%= render 'like_icon_filled' %>
      <span><%= stress_relief.likes.count %></span>
    <% end %>
  <% else %>
    <%= link_to stress_relief_likes_path(stress_relief), method: :post, data: { turbo_frame: "like_#{stress_relief.id}" }, class: "text-pink-500 hover:text-pink-300 transition duration-100 cursor-pointer mr-2 flex items-center", data: { turbo_method: "post" } do %>
      <%= render 'like_icon_outline' %>
      <span><%= stress_relief.likes.count %></span>
    <% end %>
  <% end %>
<% else %>
  <%= link_to new_user_session_path, class: "text-pink-500 hover:text-pink-300 transition duration-100 cursor-pointer mr-2 flex items-center", data: { turbo: false } do %>
    <%= render 'like_icon_outline' %>
    <span><%= stress_relief.likes.count %></span>
  <% end %>
<% end %>

app/views/stress_reliefs/_modal_stress_reliefs.html.erb
<%= turbo_frame_tag "modal_content" do %>
  <div class="flex flex-wrap justify-center">
    <% @stress_reliefs.each do |stress_relief| %>
      <div data-action="click->modal#select" class="board-item block border p-5 rounded-xl hover:scale-105 transform transition-transform duration-300 bg-white m-2 w-72 self-start" style="min-height: 400px;" data-title="<%= stress_relief.title %>" data-detail="<%= stress_relief.detail %>">
        <h2 class="font-bold text-2xl mb-4 break-all"><%= stress_relief.title %></h2>
        <% image_file = stress_relief.selected_image.presence || "stress_relief_board#{stress_relief.difficulty}.webp" %>
        <img src="<%= asset_path(image_file) %>" alt="Stress Relief Image" class="w-full h-48 object-cover mb-4">
        
        <div class="flex justify-between items-center mb-2">
          <div class="text-xl flex flex-col items-center">
            <p class="mb-1 text-base"><%= t('activerecord.attributes.stress_relief.difficulty') %></p>
            <%= render 'stress_reliefs/difficulty_stars', difficulty: stress_relief.difficulty %>
          </div>
          <div class="flex flex-wrap">
            <% stress_relief.tag_names.each do |tag_name| %>
              <span class="bg-green-200 text-gray-800 rounded-md px-2 py-1 text-sm mr-2 mb-2"><%= tag_name %></span>
            <% end %>
          </div>
        </div>

        <div class="flex justify-between items-center mt-4">
          <div class="flex items-center text-pink-500">
            <% if user_signed_in? && current_user.likes.exists?(stress_relief_id: stress_relief.id) %>
              <%= render 'likes/like_icon_filled' %>
            <% else %>
              <%= render 'likes/like_icon_outline' %>
            <% end %>
            <span class="ml-2"><%= stress_relief.likes.count %></span>
          </div>
          <p class="text-xl"><%= stress_relief.user.name %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="mt-4">
    <%= paginate @stress_reliefs, data: { turbo_frame: "modal_content" } %>
  </div>
<% end %>

app/views/stress_reliefs/_search_results.html.erb
<ul>
<% results.each do |result| %>
  <li class="w-full hover:bg-gray-300 truncate" data-result-title="<%= result.title %>"style="white-space: nowrap; overflow-x: hidden; text-overflow: ellipsis;">
    <%= result.title %>
  </li>
<% end %>
</ul>

app/views/stress_reliefs/_stress_relief.html.erb
<div class="board-item border p-5 rounded-xl bg-white m-2 w-80 self-start hover:scale-105 transform transition-transform duration-300" style="min-height: 400px;">
  <%= link_to stress_relief_path(stress_relief), class: "block " do %>
    <h2 class="font-bold text-2xl mb-4 break-all"><%= stress_relief.title %></h2>
    <% image_file = stress_relief.selected_image.presence || "stress_relief_board#{stress_relief.difficulty}.webp" %>
    <img src="<%= asset_path(image_file) %>" alt="Stress Relief Image" class="w-full h-48 object-cover mb-4">
    
    <div class="flex justify-between items-center mb-2">
      <div class="text-xl flex flex-col items-center">
        <p class="mb-1 text-base"><%= t('activerecord.attributes.stress_relief.difficulty') %></p>
        <%= render 'difficulty_stars', difficulty: stress_relief.difficulty %>
      </div>
      <div class="flex flex-wrap">
        <% stress_relief.tag_names.each do |tag_name| %>
          <span class="bg-emerald-300 text-gray-800 rounded-md px-2 py-1 text-sm mr-2 mb-2"><%= tag_name %></span>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="flex justify-between items-center mt-4">
    <%= turbo_frame_tag "like_#{stress_relief.id}" do %>
      <div class="flex items-center text-pink-500">
        <%= render 'likes/like_link', stress_relief: stress_relief %>
      </div>
    <% end %>
    <div>
      <%= link_to stress_relief.user.name, stress_relief_path(stress_relief), class: "text-xl" %>
    </div>
  </div>
</div>

app/views/stress_reliefs/index.html.erb
<div class="w-full max-w-screen-xl mx-auto p-5 bg-gray-100">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= flash[:alert] %></p>
  <% end %>

  <div class="mb-4">
    <h1 class="font-bold text-4xl inline-block"><%= t('stress_reliefs.index.title') %></h1>
    <%= link_to t('stress_reliefs.index.new_stress_relief'), new_stress_relief_path, class: "rounded-lg py-3 px-5 bg-blue-800 hover:bg-blue-700 text-white font-medium float-right" %>
    <div class="clear-both"></div>
  </div>

  <div class="text-center mb-6">
    <form action="<%= stress_reliefs_path %>" method="get" data-turbo-action="replace" data-turbo-frame="stress_reliefs" class="flex justify-between items-center">
      <div class="relative flex-grow">
        <input type="text" name="query" value="<%= params[:query] %>" data-autocomplete-input="stress_relief" placeholder="<%= t('search.input_placeholder') %>" class="border border-gray-300 p-2 rounded-md w-full shadow-sm focus:ring-indigo-700 focus:border-indigo-700">
        <div id="autocomplete-results" class="overflow-wrap break-word absolute top-full left-0 mt-2 w-full bg-white border border-gray-300 p-2 rounded-md shadow-sm divide-y divide-gray-300 hidden z-10 overflow-y-auto"></div>
      </div>
      <button type="submit" class="ml-2 bg-indigo-700 text-white p-2 rounded-md hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-700 focus:ring-opacity-50">
        <%= t('defaults.search_button') %>
      </button>
    </form>
  </div>

  <div id="stress_reliefs" class="flex flex-wrap justify-center md:justify-between">
    <%= render @stress_reliefs %>
  </div>

  <div class="w-full text-center my-8">
    <%= paginate @stress_reliefs %>
  </div>
</div>

app/views/stress_reliefs/new.html.erb
<div class="mx-auto md:w-2/3 w-full px-4">
  <h1 class="font-bold text-4xl mt-4"><%= t('stress_reliefs.new.title') %></h1>

  <%= render "form", stress_relief: @stress_relief %>

  <%= link_to t('stress_reliefs.new.back_to_stress_reliefs'), stress_reliefs_path, class: "ml-2 mb-4 rounded-lg py-3 px-5 bg-gray-300 hover:bg-gray-200 inline-block font-medium" %>
</div>

app/views/stress_reliefs/recommend.html.erb
<div id="loading" class="flex justify-center items-center h-screen">
  <span class="loading loading-ring loading-lg"></span>
</div>

<div id="recommend-content" class="w-full max-w-screen-xl mx-auto p-5 bg-gray-100 hidden">
  <h1 class="font-bold text-4xl mb-4"><%= t('stress_reliefs.recommend.title', user_name: current_user.name) %></h1>
  <div id="stress_reliefs" class="flex flex-wrap justify-center md:justify-between">
    <%= render @stress_reliefs %>
  </div>
</div>

app/views/stress_reliefs/search.turbo_stream.erb
<%= turbo_stream.update "autocomplete-results", partial: "search_results", locals: { results: @search_results } %>

app/views/stress_reliefs/user_liked.html.erb
<div class="w-full max-w-screen-xl mx-auto p-5 bg-gray-100">
  <div class="mb-4">
    <h1 class="font-bold text-4xl inline-block"><%= t('layouts.header.likes_list') %></h1>
    <div class="clear-both"></div>
  </div>

  <% if @stress_reliefs.exists? %>
    <div id="liked_stress_reliefs" class="flex flex-wrap justify-center md:justify-between">
      <%= render @stress_reliefs %>
    </div>

    <div class="w-full text-center my-8">
      <%= paginate @stress_reliefs %>
    </div>
  <% else %>
    <div class="flex flex-col items-center justify-center" style="height: 60vh;">
      <%= image_tag 'user_liked.png', alt: 'No_likes', class: 'max-w-xs' %>
      <div class="text-center mt-5">
        <p class="text-lg"><%= t('stress_reliefs.user_liked.no_likes') %></p>
        <p class="text-lg mt-2"><%= t('stress_reliefs.user_liked.find_favorites') %></p>
        <%= link_to t('home.index.view_stress_reliefs'), stress_reliefs_path, class: "mt-5 inline-block bg-blue-800 text-white py-2 px-4 rounded hover:bg-blue-700" %>
      </div>
    </div>
  <% end %>
</div>