config/routes.rb
Rails.application.routes.draw do
  resources :stress_records do
    get 'search', on: :collection
    post 'set_session', on: :member
  end
  resources :stress_reliefs do
    get 'search', on: :collection
    resources :likes, only: %i[create destroy]
  end
  devise_for :users
  get 'home/index'
  get 'terms_of_service', to: 'home#terms_of_service', as: 'terms_of_service'
  get 'privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  root 'home#index'
end

app/views/layouts/_footer.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start"></div>
  <div class="navbar-center">
    <%= link_to t('layouts.footer.terms_of_service'), terms_of_service_path, class: 'btn btn-ghost btn-sm' %>
    <%= link_to t('layouts.footer.privacy_policy'), privacy_policy_path, class: 'btn btn-ghost btn-sm' %>
  </div>
  <div class="navbar-end"></div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex flex-wrap justify-between w-full items-center">
    <div class="navbar-start mb-2 sm:mb-0">
      <%= link_to t('defaults.app_name'), root_path, class: "btn btn-ghost normal-case text-xl" %>
    </div>
    <div class="navbar-end flex-grow space-x-2 flex items-center justify-end flex-wrap">
      <div class="hidden sm:flex space-x-2">
        <%= link_to t('layouts.header.featured_stress_relief'), stress_reliefs_path, class: "btn btn-ghost btn-sm normal-case text-xs sm:text-sm" %>
        <% if user_signed_in? %>
          <%= link_to t('layouts.header.recommended_selections', user_name: current_user.name), stress_reliefs_path(recommend: true), class: "btn btn-ghost btn-sm normal-case text-xs sm:text-sm" %>
        <% end %>
      </div>
      <div class="dropdown ml-auto">
        <label tabindex="0" class="btn btn-ghost btn-circle">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
        </label>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52 origin-top-right right-0">
          <li class="sm:hidden"><%= link_to t('layouts.header.featured_stress_relief'), stress_reliefs_path %></li>
          <% if user_signed_in? %>
            <li class="sm:hidden"><%= link_to t('layouts.header.recommended_selections', user_name: current_user.name), stress_reliefs_path(recommend: true) %></li>
            <li><%= link_to t('layouts.header.record'), stress_records_path %></li>
            <li><%= link_to t('layouts.header.likes_list'), stress_reliefs_path(liked: true) %></li>
            <li><%= link_to t('defaults.logout'), destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: t('defaults.logout_message') } %></li>
          <% else %>
            <li><%= link_to t('defaults.login'), new_user_session_path %></li>
            <li><%= link_to t('defaults.sign_up'), new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('defaults.app_name') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= display_meta_tags(default_meta_tags) %>

    <%= favicon_link_tag('favicon.ico') %>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-JWY6RNZ56W"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-JWY6RNZ56W');
    </script>
  </head>

  <body class="bg-gray-100">
    <%= render 'layouts/header' %>
    <main class="w-full h-full">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>